# Generated by Django 3.2.9 on 2022-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quant', models.IntegerField()),
                ('loc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('transport', models.CharField(max_length=3)),
                ('tprice', models.IntegerField()),
            ],
        ),
    ]
